### ISSUE TITLE
Sidebar ends up in the wrong place when there is no main menu

### ISSUE THREAD

**Issue by m4xiJo** [redmine-cp/project-opal#30]
**Describe the bug**
Title says it all

**To Reproduce**
1. Go to the 'Administration' panel
2. Look at the side bar O_o

**Expected behavior**

**Additional context**

**Comment by GianVizzielli** [comment]
Is not a clean solution, but I think you can try to put here the navbar element, and add this css here only:
height: 0;
overflow: hidden;
